name: ConsoleCommandSender
main: NoobMCBG\ConsoleCommandSender\Loader
api: 4.0.0
version: 1.0.0
author: NoobMCBG
description: Use the console right in the game

permissions:
  console.control:
    description: Permissions to use the command /consolecommandsender
    default: op
